# Generated by Django 2.2 on 2019-05-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=256)),
                ('post', models.TextField()),
                ('created_date', models.DateField(auto_now=True)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('likes', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=256)),
                ('comment', models.TextField()),
                ('commented_date', models.DateField(auto_now=True)),
                ('post', models.ForeignKey(on_delete='CASCADE', related_name='comments', to='blog.PostModel')),
            ],
        ),
    ]
