# Generated by Django 2.2 on 2019-05-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='commented_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
