# Generated by Django 2.2 on 2019-05-11 18:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190511_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='commented_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
