# Generated by Django 2.2 on 2019-05-11 18:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190511_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
