# Generated by Django 2.2 on 2019-05-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190511_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
