# Generated by Django 2.2 on 2019-05-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190513_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='author',
            field=models.CharField(max_length=256),
        ),
    ]
